var lang = 
	{
		"title" : "Connaissez-vous bien votre monde ?",
		"question" : "Quel est le nom de ce pays ?",

		"ca" : "Canada", // AMERICAS
		"us" : "\311tats-Unis",
		"mx" : "Mexique",
		"gt" : "Guetemala",
		"bz" : "Belize",
		"sv" : "Salvador",
		"hn" : "Honduras",
 		"ni" : "Nicaragua",
 		"cr" : "Costa Rica",
 		"pa" : "Panama",
 		"cu" : "Cuba",
 		"bs" : "Bahamas",
 		"jm" : "Jama\357que",
 		"ht" : "Ha\357ti",
 		"do" : "R\351publique dominicaine",
 		"co" : "Colombie",
 		"ec" : "\311quateur",
 		"ve" : "Venezuela",
 		"tt" : "Trinit\351-et-Tobago",
 		"gy" : "Guyana",
 		"sr" : "Suriname",
 		"br" : "Br\351sil",
 		"pe" : "P\351rou",
 		"bo" : "Bolivie",
 		"cl" : "Chili",
 		"py" : "Paraguay",
 		"uy" : "Uruguay",
 		"ar" : "Argentine",
 		"bb" : "Barbade",
 		"ag" : "Antigua-et-Barbuda",
 		"dm" : "Dominique",
 		"gd" : "Grenade",
 		"kn" : "Saint-Christophe-et-Ni\351v\350s",
 		"lc" : "Sainte-Lucie",
 		"vc" : "Saint-Vincent-et-les Grenadines",
 		"al" : "Albanie", //EUROPE
 		"de" : "Allemagne",
 		"ad" : "Andorre",
 		"at" : "Autriche",
 		"be" : "Belgique",
 		"by" : "Bi\351lorussie",
 		"ba" : "Bosnie-Herz\351govine",
 		"bg" : "Bulgarie",
 		"cy" : "Chypre",
 		"hr" : "Croatie",
 		"dk" : "Danemark",
 		"es" : "Espagne",
 		"ee" : "Estonie",
 		"fi" : "Finlande",
 		"fr" : "France",
 		"gr" : "Gr\350ce",
 		"hu" : "Hongrie",
 		"ie" : "Irlande",
 		"is" : "Islande",
 		"it" : "Italie",
 		"lv" : "Lettonie",
 		"li" : "Liechtenstein",
 		"lt" : "Lituanie",
 		"lu" : "Luxembourg",
 		"mk" : "Mac\351doine",
 		"mt" : "Malte",
 		"md" : "Moldavie",
 		"mc" : "Monaco",
 		"me" : "Mont\351n\351gro",
 		"no" : "Norv\350ge",
 		"nl" : "Pays-Bas",
 		"pl" : "Pologne",
 		"pt" : "Portugal",
 		"ro" : "Roumanie",
 		"gb" : "Royaume-Uni",
 		"ru" : "Russie",
 		"sm" : "Saint-Marin",
 		"rs" : "Serbie",
 		"sk" : "Slovaquie",
 		"si" : "Slov\351nie",
 		"se" : "Su\350de",
 		"ch" : "Suisse",
 		"cz" : "R\351publique tch\350que",
 		"ua" : "Ukraine",
 		"va" : "Vatican",
 	};