var lang = 
	{
		"title" : "Connaissez-vous bien votre monde ?",
		"question" : "Quel est le nom de ce pays ?",

		"ca" : "Canada", // AMERICAS
		"us" : "\311tats-Unis",
		"mx" : "Mexique",
		"gt" : "Guetemala",
		"bz" : "Belize",
		"sv" : "Salvador",
		"hn" : "Honduras",
 		"ni" : "Nicaragua",
 		"cr" : "Costa Rica",
 		"pa" : "Panama",
 		"cu" : "Cuba",
 		"bs" : "Bahamas",
 		"jm" : "Jama\357que",
 		"ht" : "Ha\357ti",
 		"do" : "R\351publique dominicaine",
 		"co" : "Colombie",
 		"ec" : "\311quateur",
 		"ve" : "Venezuela",
 		"tt" : "Trinit\351-et-Tobago",
 		"gy" : "Guyana",
 		"sr" : "Suriname",
 		"br" : "Br\351sil",
 		"pe" : "P\351rou",
 		"bo" : "Bolivie",
 		"cl" : "Chili",
 		"py" : "Paraguay",
 		"uy" : "Uruguay",
 		"ar" : "Argentine",
 		"bb" : "Barbade",
 		"ag" : "Antigua-et-Barbuda",
 		"dm" : "Dominique",
 		"gd" : "Grenade",
 		"kn" : "Saint-Christophe-et-Ni\351v\350s",
 		"lc" : "Sainte-Lucie",
 		"vc" : "Saint-Vincent-et-les Grenadines",
 		"al" : "Albanie", //EUROPE
 		"de" : "Allemagne",
 		"ad" : "Andorre",
 		"at" : "Autriche",
 		"be" : "Belgique",
 		"by" : "Bi\351lorussie",
 		"ba" : "Bosnie-Herz\351govine",
 		"bg" : "Bulgarie",
 		"cy" : "Chypre",
 		"hr" : "Croatie",
 		"dk" : "Danemark",
 		"es" : "Espagne",
 		"ee" : "Estonie",
 		"fi" : "Finlande",
 		"fr" : "France",
 		"gr" : "Gr\350ce",
 		"hu" : "Hongrie",
 		"ie" : "Irlande",
 		"is" : "Islande",
 		"it" : "Italie",
 		"lv" : "Lettonie",
 		"li" : "Liechtenstein",
 		"lt" : "Lituanie",
 		"lu" : "Luxembourg",
 		"mk" : "Mac\351doine",
 		"mt" : "Malte",
 		"md" : "Moldavie",
 		"mc" : "Monaco",
 		"me" : "Mont\351n\351gro",
 		"no" : "Norv\350ge",
 		"nl" : "Pays-Bas",
 		"pl" : "Pologne",
 		"pt" : "Portugal",
 		"ro" : "Roumanie",
 		"gb" : "Royaume-Uni",
 		"ru" : "Russie",
 		"sm" : "Saint-Marin",
 		"rs" : "Serbie",
 		"sk" : "Slovaquie",
 		"si" : "Slov\351nie",
 		"se" : "Su\350de",
 		"ch" : "Suisse",
 		"cz" : "R\351publique tch\350que",
 		"ua" : "Ukraine",
 		"va" : "Vatican",
 		"za" : "Afrique du Sud", // AFRIQUE
 		"dz" : "Alg\351rie",
 		"ao" : "Angola",
 		"bj" : "B\351nin",
 		"bw" : "Botswana",
 		"bf" : "Burkina Faso",
 		"bi" : "Burundi",
 		"cm" : "Cameroun",
 		"cv" : "Cap-Vert",
 		"cf" : "Centrafrique",
 		"km" : "Comores",
 		"cg" : "R\351publique du Congo",
 		"cd" : "R\351publique d\351mocratique du Congo",
 		"ci" : "C\364te d'Ivoire",
 		"dj" : "Djibouti",
 		"eg" : "\311gypte",
 		"er" : "\311rythr\351e",
 		"et" : "\311thiopie",
 		"ga" : "Gabon",
 		"gm" : "Gambie",
 		"gh" : "Ghana",
 		"gn" : "Guin\351e",
 		"gw" : "Guin\351e-Bissau",
 		"gq" : "Guin\351e \351quatoriale",
 		"ke" : "Kenya",
 		"ls" : "Lesotho",
 		"lr" : "Liberia",
 		"ly" : "Libye",
 		"mg" : "Madagascar",
 		"mw" : "Malawi",
 		"ml" : "Mali",
 		"ma" : "Maroc",
 		"mu" : "Maurice",
 		"mr" : "Mauritanie",
 		"mz" : "Mozambique",
 		"na" : "Namibie",
 		"ne" : "Niger",
 		"ng" : "Nigeria",
 		"ug" : "Ouganda",
 		"rw" : "Rwanda",
 		"st" : "Sao Tom\351-et-Principe",
 		"sn" : "S\351n\351gal",
 		"sc" : "Seychelles",
 		"sl" : "Sierra Leone",
 		"so" : "Somalie",
 		"sd" : "Soudan",
 		"ss" : "Soudan du Sud",
 		"sz" : "Swaziland",
 		"tz" : "Tanzanie",
 		"td" : "Tchad",
 		"tg" : "Togo",
 		"tn" : "Tunisie",
 		"zm" : "Zambie",
 		"zw" : "Zimbabwe",
 		"af" : "Afghanistan", //ASIE
 		"sa" : "Arabie Saoudite",
 		"am" : "Arm\351nie",
 		"az" : "Azerba\357djan",
 		"bh" : "Bahre\357n",
 		"bd" : "Bangadlesh",
 		"bt" : "Bhoutan",
 		"mm" : "Birmanie",
 		"bn" : "Brunei",
 		"kh" : "Cambodge",
 		"cn" : "Chine",
 		"kp" : "Cor\351e du Nord",
 		"kr" : "Cor\351e du Sud",
 		"ae" : "\311mirats arabes unis",
 		"ge" : "G\351orgie",
 		"in" : "Inde",
 		"id" : "Indon\351sie",
 		"iq" : "Irak",
 		"ir" : "Iran",
 		"il" : "Isra\353l",
 		"jp" : "Japon",
 		"jo" : "Jordanie",
 		"kz" : "Kazakhstan",
 		"kg" : "Kirghizistan",
 		"kw" : "Kowe\357t",
 		"la" : "Laos",
 		"lb" : "Liban",
 		"my" : "Malaisie",
 		"mv" : "Maldives",
 		"mn" : "Mongolie",
 		"np" : "N\351pal",
 		"om" : "Oman",
 		"uz" : "Ouzb\351kistan",
 		"pk" : "Pakistan",
 		"ps" : "Palestine",
 		"ph" : "Philippines",
 		"qa" : "Qatar",
 		"sg" : "Singapour",
 		"lk" : "Sri Lanka",
 		"sy" : "Syrie",
 		"tj" : "Tadjikistan",
 		"th" : "Tha\357lande",
 		"tl" : "Timor oriental",
 		"tm" : "Turkm\351nistan",
 		"tr" : "Turquie",
 		"vn" : "Vi\353t Nam",
 		"ye" : "Y\351men",
};