var lang = 
	{
		"title" : "Quizz - Pays du monde",
		"question" : "Entrez le nom d'un pays :",
		"clear" : "Vider la carte",

		// AMERICAS
		"canada" : "ca", 
		"etats unis" : "us",
		"usa" : "us",
		"mexique" : "mx",
		"guatemala" : "gt",
		"belize" : "bz",
		"salvador" : "sv",
		"honduras" : "hn",
 		"nicaragua" : "ni",
 		"costa rica" : "cr",
 		"panama" : "pa",
 		"cuba" : "cu",
 		"bahamas" : "bs",
 		"jamaique" : "jm",
 		"haiti" : "ht",
 		"republique dominicaine" : "do",
 		"colombie" : "co",
 		"equateur" : "ec",
 		"venezuela" : "ve",
 		"trinite et tobago" : "tt",
 		"guyana" : "gy",
 		"suriname" : "sr",
 		"bresil" : "br",
 		"perou" : "pe",
 		"bolivie" : "bo",
 		"chili" : "cl",
 		"paraguay" : "py",
 		"uruguay" : "uy",
 		"argentine" : "ar",
 		"barbade" : "bb",
 		"antigua et barbuda" : "ag",
 		"dominique" : "dm",
 		"grenade" : "gd",
 		"saint christophe et nieves" : "kn",
 		"sainte lucie" : "lc",
 		"saint vincent et les grenadines" : "vc",
 		//EUROPE
 		"albanie" : "al", 
 		"allemagne" : "de",
 		"andorre" : "ad",
 		"autriche" : "at",
 		"belgique" : "be",
 		"bielorussie" : "by",
 		"bosnie herzegovine" : "ba",
 		"bulgarie" : "bg",
 		"chypre" : "cy",
 		"croatie" : "hr",
 		"danemark" : "dk",
 		"espagne" : "es",
 		"estonie" : "ee",
 		"finlande" : "fi",
 		"france" : "fr",
 		"grece" : "gr",
 		"hongrie" : "hu",
 		"irlande" : "ie",
 		"islande" : "is",
 		"italie" : "it",
 		"kosovo" : "xk",
 		"lettonie" : "lv",
 		"liechtenstein" : "li",
 		"lituanie" : "lt",
 		"luxembourg" : "lu",
 		"macedoine" : "mk",
 		"malte" : "mt",
 		"moldavie" : "md",
 		"monaco" : "mc",
 		"montenegro" : "me",
 		"norvege" : "no",
 		"pays bas" : "nl",
 		"pologne" : "pl",
 		"portugal" : "pt",
 		"roumanie" : "ro",
 		"royaume uni" : "gb",
 		"russie" : "ru",
 		"saint marin" : "sm",
 		"serbie" : "rs",
 		"slovaquie" : "sk",
 		"slovenie" : "si",
 		"suede" : "se",
 		"suisse" : "ch",
 		"republique tcheque" : "cz",
 		"ukraine" : "ua",
 		"vatican" : "va",
 		// AFRIQUE
 		"afrique du sud" : "za", 
 		"algerie" : "dz",
 		"angola" : "ao",
 		"benin" : "bj",
 		"botswana" : "bw",
 		"burkina faso" : "bf",
 		"burundi" : "bi",
 		"cameroun" : "cm",
 		"cap vert" : "cv",
 		"centrafrique" : "cf",
 		"comores" : "km",
 		"republique du congo" : "cg",
 		"congo" : "cg",
 		"republique democratique du congo" : "cd",
 		"cote d ivoire" : "ci",
 		"djibouti" : "dj",
 		"egypte" : "eg",
 		"erythree" : "er",
 		"ethiopie" : "et",
 		"gabon" : "ga",
 		"gambie" : "gm",
 		"ghana" : "gh",
 		"guinee" : "gn",
 		"guinee bissau" : "gw",
 		"guinee equatoriale" : "gq",
 		"kenya" : "ke",
 		"lesotho" : "ls",
 		"liberia" : "lr",
 		"libye" : "ly",
 		"madagascar" : "mg",
 		"malawi" : "mw",
 		"mali" : "ml",
 		"maroc" : "ma",
 		"maurice" : "mu",
 		"mauritanie" : "mr",
 		"mozambique" : "mz",
 		"namibie" : "na",
 		"niger" : "ne",
 		"nigeria" : "ng",
 		"ouganda" : "ug",
 		"rwanda" : "rw",
 		"sao tome et principe" : "st",
 		"senegal" : "sn",
 		"seychelles" : "sc",
 		"sierra leone" : "sl",
 		"somalie" : "so",
 		"soudan" : "sd",
 		"soudan du sud" : "ss",
 		"swaziland" : "sz",
 		"tanzanie" : "tz",
 		"tchad" : "td",
 		"togo" : "tg",
 		"tunisie" : "tn",
 		"zambie" : "zm",
 		"zimbabwe" : "zw",
 		//ASIE
 		"afghanistan" : "af", 
 		"arabie saoudite" : "sa",
 		"armenie" : "am",
 		"azerbaidjan" : "az",
 		"bahrein" : "bh",
 		"bangadlesh" : "bd",
 		"bhoutan" : "bt",
 		"birmanie" : "mm",
 		"brunei" : "bn",
 		"cambodge" : "kh",
 		"chine" : "cn",
 		"coree du nord" : "kp",
 		"coree du sud" : "kr",
 		"emirats arabes unis" : "ae",
 		"georgie" : "ge",
 		"inde" : "in",
 		"indonesie" : "id",
 		"irak" : "iq",
 		"iran" : "ir",
 		"israel" : "il",
 		"japon" : "jp",
 		"jordanie" : "jo",
 		"kazakhstan" : "kz",
 		"kirghizistan" : "kg",
 		"koweit" : "kw",
 		"laos" : "la",
 		"liban" : "lb",
 		"malaisie" : "my",
 		"maldives" : "mv",
 		"mongolie" : "mn",
 		"nepal" : "np",
 		"oman" : "om",
 		"ouzbekistan" : "uz",
 		"pakistan" : "pk",
 		"palestine" : "ps",
 		"philippines" : "ph",
 		"qatar" : "qa",
 		"singapour" : "sg",
 		"sri lanka" : "lk",
 		"syrie" : "sy",
 		"tadjikistan" : "tj",
 		"thailande" : "th",
 		"timor oriental" : "tl",
 		"turkmenistan" : "tm",
 		"turquie" : "tr",
 		"viet nam" : "vn",
 		"vietnam" : "vn",
 		"yemen" : "ye",
 		// OCEANIE
 		"australie" : "au", 
 		"fidji" : "fj",
 		"kiribati" : "ki",
 		"iles marshall" : "mh",
 		"micronesie" : "fm",
 		"nauru" : "nr",
 		"nouvelle zelande" : "nz",
 		"palaos" : "pw",
 		"papouasie nouvelle guinee" : "pg",
 		"salomon" : "sb",
 		"samoa" : "ws",
 		"tonga" : "to",
 		"tuvalu" : "tv",
 		"vanuatu" : "vu",
 		"iles cook" : "ck",
 		"niue" : "nu",

		// AMERICAS
		"ca" : "Canada", 
		"us" : "\311tats-Unis",
		"mx" : "Mexique",
		"gt" : "Guatemala",
		"bz" : "Belize",
		"sv" : "Salvador",
		"hn" : "Honduras",
 		"ni" : "Nicaragua",
 		"cr" : "Costa Rica",
 		"pa" : "Panama",
 		"cu" : "Cuba",
 		"bs" : "Bahamas",
 		"jm" : "Jama\357que",
 		"ht" : "Ha\357ti",
 		"do" : "R\351publique dominicaine",
 		"co" : "Colombie",
 		"ec" : "\311quateur",
 		"ve" : "Venezuela",
 		"tt" : "Trinit\351-et-Tobago",
 		"gy" : "Guyana",
 		"sr" : "Suriname",
 		"br" : "Br\351sil",
 		"pe" : "P\351rou",
 		"bo" : "Bolivie",
 		"cl" : "Chili",
 		"py" : "Paraguay",
 		"uy" : "Uruguay",
 		"ar" : "Argentine",
 		"bb" : "Barbade",
 		"ag" : "Antigua-et-Barbuda",
 		"dm" : "Dominique",
 		"gd" : "Grenade",
 		"kn" : "Saint-Christophe-et-Ni\351v\350s",
 		"lc" : "Sainte-Lucie",
 		"vc" : "Saint-Vincent-et-les Grenadines",
 		"al" : "Albanie", 
 		"de" : "Allemagne",
 		"ad" : "Andorre",
 		"at" : "Autriche",
 		"be" : "Belgique",
 		"by" : "Bi\351lorussie",
 		"ba" : "Bosnie-Herz\351govine",
 		"bg" : "Bulgarie",
 		"cy" : "Chypre",
 		"hr" : "Croatie",
 		"dk" : "Danemark",
 		"es" : "Espagne",
 		"ee" : "Estonie",
 		"fi" : "Finlande",
 		"fr" : "France",
 		"gr" : "Gr\350ce",
 		"hu" : "Hongrie",
 		"ie" : "Irlande",
 		"is" : "Islande",
 		"it" : "Italie",
 		"xk" : "Kosovo",
 		"lv" : "Lettonie",
 		"li" : "Liechtenstein",
 		"lt" : "Lituanie",
 		"lu" : "Luxembourg",
 		"mk" : "Mac\351doine",
 		"mt" : "Malte",
 		"md" : "Moldavie",
 		"mc" : "Monaco",
 		"me" : "Mont\351n\351gro",
 		"no" : "Norv\350ge",
 		"nl" : "Pays-Bas",
 		"pl" : "Pologne",
 		"pt" : "Portugal",
 		"ro" : "Roumanie",
 		"gb" : "Royaume-Uni",
 		"ru" : "Russie",
 		"sm" : "Saint-Marin",
 		"rs" : "Serbie",
 		"sk" : "Slovaquie",
 		"si" : "Slov\351nie",
 		"se" : "Su\350de",
 		"ch" : "Suisse",
 		"cz" : "R\351publique tch\350que",
 		"ua" : "Ukraine",
 		"va" : "Vatican",
 		"za" : "Afrique du Sud", 
 		"dz" : "Alg\351rie",
 		"ao" : "Angola",
 		"bj" : "B\351nin",
 		"bw" : "Botswana",
 		"bf" : "Burkina Faso",
 		"bi" : "Burundi",
 		"cm" : "Cameroun",
 		"cv" : "Cap-Vert",
 		"cf" : "Centrafrique",
 		"km" : "Comores",
 		"cg" : "R\351publique du Congo",
 		"cd" : "R\351publique d\351mocratique du Congo",
 		"ci" : "C\364te d'Ivoire",
 		"dj" : "Djibouti",
 		"eg" : "\311gypte",
 		"er" : "\311rythr\351e",
 		"et" : "\311thiopie",
 		"ga" : "Gabon",
 		"gm" : "Gambie",
 		"gh" : "Ghana",
 		"gn" : "Guin\351e",
 		"gw" : "Guin\351e-Bissau",
 		"gq" : "Guin\351e \351quatoriale",
 		"ke" : "Kenya",
 		"ls" : "Lesotho",
 		"lr" : "Liberia",
 		"ly" : "Libye",
 		"mg" : "Madagascar",
 		"mw" : "Malawi",
 		"ml" : "Mali",
 		"ma" : "Maroc",
 		"mu" : "Maurice",
 		"mr" : "Mauritanie",
 		"mz" : "Mozambique",
 		"na" : "Namibie",
 		"ne" : "Niger",
 		"ng" : "Nigeria",
 		"ug" : "Ouganda",
 		"rw" : "Rwanda",
 		"st" : "Sao Tom\351-et-Principe",
 		"sn" : "S\351n\351gal",
 		"sc" : "Seychelles",
 		"sl" : "Sierra Leone",
 		"so" : "Somalie",
 		"sd" : "Soudan",
 		"ss" : "Soudan du Sud",
 		"sz" : "Swaziland",
 		"tz" : "Tanzanie",
 		"td" : "Tchad",
 		"tg" : "Togo",
 		"tn" : "Tunisie",
 		"zm" : "Zambie",
 		"zw" : "Zimbabwe",
 		"af" : "Afghanistan", 
 		"sa" : "Arabie Saoudite",
 		"am" : "Arm\351nie",
 		"az" : "Azerba\357djan",
 		"bh" : "Bahre\357n",
 		"bd" : "Bangadlesh",
 		"bt" : "Bhoutan",
 		"mm" : "Birmanie",
 		"bn" : "Brunei",
 		"kh" : "Cambodge",
 		"cn" : "Chine",
 		"kp" : "Cor\351e du Nord",
 		"kr" : "Cor\351e du Sud",
 		"ae" : "\311mirats arabes unis",
 		"ge" : "G\351orgie",
 		"in" : "Inde",
 		"id" : "Indon\351sie",
 		"iq" : "Irak",
 		"ir" : "Iran",
 		"il" : "Isra\353l",
 		"jp" : "Japon",
 		"jo" : "Jordanie",
 		"kz" : "Kazakhstan",
 		"kg" : "Kirghizistan",
 		"kw" : "Kowe\357t",
 		"la" : "Laos",
 		"lb" : "Liban",
 		"my" : "Malaisie",
 		"mv" : "Maldives",
 		"mn" : "Mongolie",
 		"np" : "N\351pal",
 		"om" : "Oman",
 		"uz" : "Ouzb\351kistan",
 		"pk" : "Pakistan",
 		"ps" : "Palestine",
 		"ph" : "Philippines",
 		"qa" : "Qatar",
 		"sg" : "Singapour",
 		"lk" : "Sri Lanka",
 		"sy" : "Syrie",
 		"tj" : "Tadjikistan",
 		"th" : "Tha\357lande",
 		"tl" : "Timor oriental",
 		"tm" : "Turkm\351nistan",
 		"tr" : "Turquie",
 		"vn" : "Vi\353t Nam",
 		"ye" : "Y\351men",
 		"au" : "Australie", 
 		"fj" : "Fidji",
 		"ki" : "Kiribati",
 		"mh" : "\316les Marshall",
 		"fm" : "Micron\351sie",
 		"nr" : "Nauru",
 		"nz" : "Nouvelle-Z\351lande",
 		"pw" : "Palaos",
 		"pg" : "Papouasie-Nouvelle-Guin\351e",
 		"sb" : "Salomon",
 		"ws" : "Samoa",
 		"to" : "Tonga",
 		"tv" : "Tuvalu",
 		"vu" : "Vanuatu",
 		"ck" : "\316les Cook",
 		"nu" : "Niue"
};